Xtest = read.table('./data/X_test.txt')
ytest = read.table('./data/y_test.txt')
Xtrain = read.table('./data/X_train.txt')
ytrain = read.table('./data/y_train.txt')
labs= c('WALKING','WALKING_UPSTAIRS','WALKING_DOWNSTAIRS','SITTING','STANDING','LAYING')
names(labs) = c(1,2,3,4,5,6)
X = rbind(Xtrain,Xtest)
y = rbind(ytrain,ytest)
X = as.matrix(X)
m = apply(X,1, mean)
s = apply(X,1, sd)
df = as.data.frame(cbind(m,s,y))
df$V1 = labs[df$V1]
names(df) = c('Means','Stds','Activities')
out = aggregate(df[-3],by=list(df$Activities),mean)
write.table(out,'results.txt',row.name=FALSE)
out